/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

/**
 *
 * @author dell
 */
public class Configuracion extends javax.swing.JFrame {
    ModoJuego modoJuego = new ModoJuego();
    
    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Expert = new javax.swing.JButton();
        Genius = new javax.swing.JButton();
        Normal = new javax.swing.JButton();
        Aleatorio = new javax.swing.JButton();
        Manual = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 1, 50)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Modo de Juego");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, 90));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 1, 100)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Configuración");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 40, 460, 90));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 1, 50)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Dificultad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 90));

        Expert.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 18)); // NOI18N
        Expert.setText("Expert");
        Expert.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Expert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpertMouseClicked(evt);
            }
        });
        Expert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertActionPerformed(evt);
            }
        });
        getContentPane().add(Expert, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 90, 40));

        Genius.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 18)); // NOI18N
        Genius.setText("Genius");
        Genius.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Genius.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeniusMouseClicked(evt);
            }
        });
        Genius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeniusActionPerformed(evt);
            }
        });
        getContentPane().add(Genius, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 90, 40));

        Normal.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 18)); // NOI18N
        Normal.setText("Normal");
        Normal.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Normal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NormalMouseClicked(evt);
            }
        });
        Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalActionPerformed(evt);
            }
        });
        getContentPane().add(Normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 90, 40));

        Aleatorio.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 18)); // NOI18N
        Aleatorio.setText("Aleatorio");
        Aleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AleatorioActionPerformed(evt);
            }
        });
        getContentPane().add(Aleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 90, 40));

        Manual.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 18)); // NOI18N
        Manual.setText("Manual");
        Manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualActionPerformed(evt);
            }
        });
        getContentPane().add(Manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 90, 40));

        Salir.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 18)); // NOI18N
        Salir.setText("Regresar");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 100, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExpertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertActionPerformed
        modoJuego.setModoJuegoDif("Expert");

    }//GEN-LAST:event_ExpertActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalActionPerformed
        modoJuego.setModoJuegoDif("Normal");
        
    }//GEN-LAST:event_NormalActionPerformed

    private void GeniusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeniusActionPerformed
        modoJuego.setModoJuegoDif("Genius");

    }//GEN-LAST:event_GeniusActionPerformed

    private void NormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NormalMouseClicked
        modoJuego.setModoJuegoDif("Normal");
    }//GEN-LAST:event_NormalMouseClicked

    private void ExpertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpertMouseClicked
        modoJuego.setModoJuegoDif("Expert");
    }//GEN-LAST:event_ExpertMouseClicked

    private void GeniusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeniusMouseClicked
        modoJuego.setModoJuegoDif("Genius");
    }//GEN-LAST:event_GeniusMouseClicked

    private void AleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AleatorioActionPerformed
      ModoJuego.setModoDeJuego("Aleatorio");
    }//GEN-LAST:event_AleatorioActionPerformed

    private void ManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualActionPerformed
        ModoJuego.setModoDeJuego("Manual");
    }//GEN-LAST:event_ManualActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aleatorio;
    private javax.swing.JButton Expert;
    private javax.swing.JButton Genius;
    private javax.swing.JButton Manual;
    private javax.swing.JButton Normal;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
