/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class Juego extends javax.swing.JFrame {
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonF1C1 = new javax.swing.JButton();
        BotonF1C2 = new javax.swing.JButton();
        BotonF1C3 = new javax.swing.JButton();
        BotonF1C4 = new javax.swing.JButton();
        BotonF1C5 = new javax.swing.JButton();
        BotonF1C6 = new javax.swing.JButton();
        BotonF2C1 = new javax.swing.JButton();
        BotonF2C2 = new javax.swing.JButton();
        BotonF2C3 = new javax.swing.JButton();
        BotonF2C4 = new javax.swing.JButton();
        BotonF2C5 = new javax.swing.JButton();
        BotonF2C6 = new javax.swing.JButton();
        BotonF3C1 = new javax.swing.JButton();
        BotonF3C2 = new javax.swing.JButton();
        BotonF3C3 = new javax.swing.JButton();
        BotonF3C4 = new javax.swing.JButton();
        BotonF3C5 = new javax.swing.JButton();
        BotonF3C6 = new javax.swing.JButton();
        BotonF4C1 = new javax.swing.JButton();
        BotonF4C2 = new javax.swing.JButton();
        BotonF4C3 = new javax.swing.JButton();
        BotonF4C4 = new javax.swing.JButton();
        BotonF4C5 = new javax.swing.JButton();
        BotonF4C6 = new javax.swing.JButton();
        BotonF5C1 = new javax.swing.JButton();
        BotonF5C2 = new javax.swing.JButton();
        BotonF5C3 = new javax.swing.JButton();
        BotonF5C4 = new javax.swing.JButton();
        BotonF5C5 = new javax.swing.JButton();
        BotonF5C6 = new javax.swing.JButton();
        BotonF6C1 = new javax.swing.JButton();
        BotonF6C2 = new javax.swing.JButton();
        BotonF6C3 = new javax.swing.JButton();
        BotonF6C4 = new javax.swing.JButton();
        BotonF6C5 = new javax.swing.JButton();
        BotonF6C6 = new javax.swing.JButton();
        Rendirte = new javax.swing.JButton();
        LabelJug2 = new javax.swing.JLabel();
        LabelTurno = new javax.swing.JLabel();
        LabelJug1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(6, 6));

        BotonF1C1.setBackground(new java.awt.Color(0, 51, 102));
        BotonF1C1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF1C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF1C1);

        BotonF1C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo1.png"))); // NOI18N
        BotonF1C2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF1C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF1C2);

        BotonF1C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo1.png"))); // NOI18N
        BotonF1C3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF1C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF1C3);

        BotonF1C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo1.png"))); // NOI18N
        BotonF1C4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF1C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF1C4);

        BotonF1C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo1.png"))); // NOI18N
        BotonF1C5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF1C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF1C5);

        BotonF1C6.setBackground(new java.awt.Color(0, 51, 102));
        BotonF1C6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF1C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF1C6);

        BotonF2C1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF2C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF2C1);

        BotonF2C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo1.png"))); // NOI18N
        BotonF2C2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF2C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF2C2);

        BotonF2C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo1.png"))); // NOI18N
        BotonF2C3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF2C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF2C3);

        BotonF2C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo1.png"))); // NOI18N
        BotonF2C4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF2C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF2C4);

        BotonF2C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo1.png"))); // NOI18N
        BotonF2C5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF2C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF2C5);

        BotonF2C6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF2C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF2C6);

        BotonF3C1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF3C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF3C1);

        BotonF3C2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF3C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF3C2);

        BotonF3C3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF3C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF3C3);

        BotonF3C4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF3C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF3C4);

        BotonF3C5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF3C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF3C5);

        BotonF3C6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF3C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF3C6);

        BotonF4C1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF4C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF4C1);

        BotonF4C2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF4C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF4C2);

        BotonF4C3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF4C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF4C3);

        BotonF4C4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF4C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF4C4);

        BotonF4C5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF4C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF4C5);

        BotonF4C6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF4C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF4C6);

        BotonF5C1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF5C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF5C1);

        BotonF5C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo2.png"))); // NOI18N
        BotonF5C2.setToolTipText("");
        BotonF5C2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF5C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF5C2);

        BotonF5C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo2.png"))); // NOI18N
        BotonF5C3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF5C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF5C3);

        BotonF5C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo2.png"))); // NOI18N
        BotonF5C4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF5C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF5C4);

        BotonF5C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo2.png"))); // NOI18N
        BotonF5C5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF5C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF5C5);

        BotonF5C6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF5C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF5C6);

        BotonF6C1.setBackground(new java.awt.Color(0, 51, 102));
        BotonF6C1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF6C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF6C1);

        BotonF6C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo2.png"))); // NOI18N
        BotonF6C2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF6C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF6C2);

        BotonF6C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo2.png"))); // NOI18N
        BotonF6C3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF6C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF6C3);

        BotonF6C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo2.png"))); // NOI18N
        BotonF6C4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF6C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF6C4);

        BotonF6C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fantasmaNuevo2.png"))); // NOI18N
        BotonF6C5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF6C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF6C5);

        BotonF6C6.setBackground(new java.awt.Color(0, 51, 102));
        BotonF6C6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonF6C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonF1C1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonF6C6);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 660, 490));

        Rendirte.setText("Rendirte");
        Rendirte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RendirteActionPerformed(evt);
            }
        });
        getContentPane().add(Rendirte, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 110, 30));

        LabelJug2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        LabelJug2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJug2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LabelJug2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Jugador 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gigi", 1, 14))); // NOI18N
        getContentPane().add(LabelJug2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 110, 180));

        LabelTurno.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 14)); // NOI18N
        LabelTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTurno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "TURNO ACTUAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Ext Condensed Bold", 1, 14))); // NOI18N
        getContentPane().add(LabelTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 180, 40));

        LabelJug1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        LabelJug1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJug1.setToolTipText("");
        LabelJug1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LabelJug1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Jugador 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gigi", 1, 14))); // NOI18N
        getContentPane().add(LabelJug1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 180));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo 3.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RendirteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RendirteActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres rendirte?", "Confirmar rendición", JOptionPane.YES_NO_OPTION);
    
        if (respuesta == JOptionPane.YES_OPTION) {
            MenuPrincipal menuPrincipal = new MenuPrincipal();
            menuPrincipal.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_RendirteActionPerformed

    private void BotonF1C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonF1C1ActionPerformed
        
    }//GEN-LAST:event_BotonF1C1ActionPerformed
    
    private void BotonF1C2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BotonF1C1;
    public static javax.swing.JButton BotonF1C2;
    public static javax.swing.JButton BotonF1C3;
    public static javax.swing.JButton BotonF1C4;
    public static javax.swing.JButton BotonF1C5;
    public static javax.swing.JButton BotonF1C6;
    public static javax.swing.JButton BotonF2C1;
    public static javax.swing.JButton BotonF2C2;
    public static javax.swing.JButton BotonF2C3;
    public static javax.swing.JButton BotonF2C4;
    public static javax.swing.JButton BotonF2C5;
    public static javax.swing.JButton BotonF2C6;
    public static javax.swing.JButton BotonF3C1;
    public static javax.swing.JButton BotonF3C2;
    public static javax.swing.JButton BotonF3C3;
    public static javax.swing.JButton BotonF3C4;
    public static javax.swing.JButton BotonF3C5;
    public static javax.swing.JButton BotonF3C6;
    public static javax.swing.JButton BotonF4C1;
    public static javax.swing.JButton BotonF4C2;
    public static javax.swing.JButton BotonF4C3;
    public static javax.swing.JButton BotonF4C4;
    public static javax.swing.JButton BotonF4C5;
    public static javax.swing.JButton BotonF4C6;
    public static javax.swing.JButton BotonF5C1;
    public static javax.swing.JButton BotonF5C2;
    public static javax.swing.JButton BotonF5C3;
    public static javax.swing.JButton BotonF5C4;
    public static javax.swing.JButton BotonF5C5;
    public static javax.swing.JButton BotonF5C6;
    public static javax.swing.JButton BotonF6C1;
    public static javax.swing.JButton BotonF6C2;
    public static javax.swing.JButton BotonF6C3;
    public static javax.swing.JButton BotonF6C4;
    public static javax.swing.JButton BotonF6C5;
    public static javax.swing.JButton BotonF6C6;
    public static javax.swing.JLabel LabelJug1;
    public static javax.swing.JLabel LabelJug2;
    public static javax.swing.JLabel LabelTurno;
    private javax.swing.JButton Rendirte;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
